---
title: "Smash Bros"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r libraries, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(scales)
library(zoo)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(toOrdinal)
library(shiny)
library(DT)
library(rsconnect)
library(readxl)

```


```{r DataReadSmash ,include=FALSE}
## Read in data
RawSmashData <- readxl::read_excel("SSBU Code.xlsx")

## Reset point
SmashData <- RawSmashData

## Filtering out extra columns to the right
SmashData <- SmashData %>%
  select(Game:DamageGiven)

## Adding in an Opponent Character Column
SmashData <- SmashData %>%
  left_join(SmashData ,by = c("Game" ,"Date" ,"Opponent" = "Player"))

## Adjusting the column names after the join
colnames(SmashData) <- c("Game" ,"Date" ,"Player" ,"Opponent" ,"Character" ,"Win" ,"KO" ,"DamageGiven" ,"Player2" ,"OpponentCharacter" ,"OpponentWin" ,"OpponentKO" ,"OpponentDamageGiven")

## Removing unnecessary Player2 column & re-ordering columns
SmashData <- SmashData %>%
  select(Game:Player ,Character:DamageGiven ,Opponent ,OpponentCharacter:OpponentDamageGiven)

## Fixing my name
SmashData <- SmashData %>%
  mutate(Player = ifelse(Player == "Robert" ,"RoBert" ,Player)
         ,Opponent = ifelse(Opponent == "Robert" ,"RoBert" ,Opponent))

## Getting list of Players
PlayerNames <- SmashData %>%
  select(Player) %>%
  unique() 

## Getting Player with Best Win Percent
TopPlayer <- SmashData %>%
  group_by(Player) %>%
  summarise(WinPercent = sum(Win) / n()) %>%
  top_n(WinPercent ,n = 1) %>%
  select(Player) %>%
  as.character()

TopWinPercent <- SmashData %>%
  group_by(Player) %>%
  summarise(WinPercent = sum(Win) / n()) %>%
  top_n(WinPercent ,n = 1) %>%
  select(WinPercent) %>%
  as.numeric() 

BottomWinPercent <- SmashData %>%
  group_by(Player) %>%
  summarise(WinPercent = sum(Win) / n()) %>%
  top_n(WinPercent ,n = -1) %>%
  select(WinPercent) %>%
  as.numeric()

## Getting Win Percent data by player
WinPercentData <- SmashData %>%
  group_by(Player) %>%
  summarise(WinPercent = scales::percent(sum(Win) / n())
            ,WinPercentUnformatted = sum(Win) / n())

```

Player Stats {data-navmenu="Smash Stats"}
=======================================================================

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------
```{r}

selectInput("PlayerInput"
            ,"Select a player:"
            ,choices = PlayerNames$Player
            ,selected = TopPlayer)

```



Column {data-width=450}
-----------------------------------------------------------------------

### Current Win Percent

```{r}

ReactiveWinPercentData <- reactive({
  WinPercentData %>%
    filter(Player == input$PlayerInput)
})

renderValueBox(
  valueBox(ReactiveWinPercentData() %>% select(WinPercent)
           ,icon = "fa-trophy"
           ,color = ifelse(ReactiveWinPercentData() %>% select(WinPercentUnformatted) %>% as.numeric() >= floor(TopWinPercent / .01) * .01, "success", ifelse(ReactiveWinPercentData() %>% select(WinPercentUnformatted) %>% as.numeric() <= ceiling(BottomWinPercent/ .01) * .01 ,"danger" ,"warning")))
)

```

### Longest Win Streak

```{r}

ReactiveLongestWinStreak <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    summarise(LongestWinStreak2 = max(rle(Win == 1)[[1]][rle(Win == 1)[[2]] == 1])) %>%
    as.numeric()
})


renderValueBox(
  valueBox(ReactiveLongestWinStreak()
           ,color = ifelse(ReactiveLongestWinStreak() < 2 ,"danger" ,ifelse(ReactiveLongestWinStreak() < 5  ,"warning" ,"success")))
)

```

### Win Percent Against Character

```{r}

ReactiveWinPercentAgainstCharacter <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    group_by(Player ,OpponentCharacter) %>%
    summarise(WinPercent = sum(WinPercent = sum(Win) / n())) %>%
    left_join(WinPercentData %>% select(Player ,WinPercentUnformatted) ,by = "Player") 
})

renderPlot({
  ggplot(ReactiveWinPercentAgainstCharacter() ,aes(x = reorder(OpponentCharacter ,WinPercent ,function(x) {x}) ,y = WinPercent ,fill = WinPercent)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(limits = c(0 ,1) ,labels = scales::percent) +
    geom_hline(yintercept = ReactiveWinPercentAgainstCharacter() %>% select(WinPercentUnformatted) %>% unique() %>% as.numeric()) +  
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,1) ,labels = scales::percent) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() +
    theme(legend.position = "none")     
})

```


### Win Percent Against Opponent

```{r}

ReactiveWinPercentAgainstOpponent <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    group_by(Player ,Opponent) %>%
    summarise(WinPercent = sum(WinPercent = sum(Win) / n())) %>%
    left_join(WinPercentData %>% select(Player ,WinPercentUnformatted) ,by = "Player")
})


renderPlot({
  ggplot(ReactiveWinPercentAgainstOpponent() ,aes(x = reorder(Opponent ,WinPercent ,function(x) {x}) ,y = WinPercent ,fill = WinPercent)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(limits = c(0 ,1) ,labels = scales::percent) +
    geom_hline(yintercept = ReactiveWinPercentAgainstOpponent() %>% select(WinPercentUnformatted) %>% unique() %>% as.numeric()) +     
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,1) ,labels = scales::percent) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight() +
    theme(legend.position = "none")
})

```


Column {data-width=350}
-----------------------------------------------------------------------

### Total Games Played

```{r}

ReactiveGamesPlayedData <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    summarise(GamesPlayed = n())
})

renderValueBox(
  valueBox(ReactiveGamesPlayedData() %>% select(GamesPlayed)
           ,icon = "fa-gamepad")
)


```


### Current Win Streak

```{r}
ReactiveCurrentWinStreak <- reactive({
  SmashData %>%  
    filter(Player == input$PlayerInput) %>%
    select(Win) %>%
    summarise(Current = ifelse(rle(Win)$values[length(rle(Win)$values)] == 0 ,0 ,rle(Win)$lengths[length(rle(Win)$lengths)])) %>%
    as.numeric()
})


renderValueBox(
  valueBox(ReactiveCurrentWinStreak()
           ,color = ifelse(ReactiveCurrentWinStreak() == 0, "danger" ,ifelse(ReactiveCurrentWinStreak() < 2  ,"warning" ,"success")))
)



```

### Games Played Against Character

```{r}

ReactiveGamesPlayedAgainstCharacter <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    group_by(OpponentCharacter) %>%
    summarise(GamesPlayed = n())
})


renderPlot({
  ggplot(ReactiveGamesPlayedAgainstCharacter() ,aes(x = reorder(OpponentCharacter ,GamesPlayed ,function(x) {x}) ,y = GamesPlayed)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,1)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```


### Games Played Against Opponent

```{r}

ReactiveGamesPlayedAgainstOpponent <- reactive({
  SmashData %>%
    filter(Player == input$PlayerInput) %>%
    group_by(Opponent) %>%
    summarise(GamesPlayed = n())
})


renderPlot({
  ggplot(ReactiveGamesPlayedAgainstOpponent() ,aes(x = reorder(Opponent ,GamesPlayed ,function(x) {x}) ,y = GamesPlayed)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,1)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```

Cross Player Comparisons {data-navmenu="Smash Stats"}
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Win Percent by Player

```{r}

renderPlot({
  ggplot(WinPercentData ,aes(x = reorder(Player ,WinPercentUnformatted ,function(x) {x}) ,y = WinPercentUnformatted)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(limits = c(0 ,1) ,labels = scales::percent) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,MaxWeeksAsKing)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```

### Avg Damage Given by Player

```{r}

DamageGivenByPlayer <- SmashData %>%
  group_by(Player) %>%
  summarise(AvgDamageGiven = mean(DamageGiven))

renderPlot({
  ggplot(DamageGivenByPlayer ,aes(x = reorder(Player ,AvgDamageGiven ,function(x) {x}) ,y = AvgDamageGiven)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,MaxWeeksAsKing)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```

Column {data-width=500}
-----------------------------------------------------------------------

### Avg KO's by Player

```{r}
KosByPlayer <- SmashData %>%
  group_by(Player) %>%
  summarise(AvgKos = mean(KO))


renderPlot({
  ggplot(KosByPlayer ,aes(x = reorder(Player ,AvgKos ,function(x) {x}) ,y = AvgKos)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,MaxWeeksAsKing)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```

### Total Games Played

```{r}

GamesPlayedByPlayer <- SmashData %>%
  group_by(Player) %>%
  summarise(GamesPlayed = n())

renderPlot({
  ggplot(GamesPlayedByPlayer ,aes(x = reorder(Player ,GamesPlayed ,function(x) {x}) ,y = GamesPlayed)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = scales::comma) +
    # ggtitle("Points by Player") +
    # theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Player") +
    # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen") ,limit = c(0 ,MaxWeeksAsKing)) +    
    # scale_fill_brewer(palette = "Set1") +
    theme_fivethirtyeight()      
})

```
